# Generated by Django 3.2 on 2023-01-04 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador_Estrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, default='', max_length=150, verbose_name='Indicador')),
                ('instituicao', models.CharField(choices=[('Sesi', 'SESI'), ('Senai', 'SENAI')], default='SENAI', max_length=11)),
                ('objetivo_estrategico', models.CharField(db_index=True, default='', max_length=150, verbose_name='Objetivo Estratégico')),
            ],
            options={
                'verbose_name': 'Indicador Estratégico',
                'verbose_name_plural': 'Indicadores Estratégicos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Perspectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Perspectiva',
                'verbose_name_plural': 'Perspectivas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Pilar',
                'verbose_name_plural': 'Pilares',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Plano_Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, default='', max_length=255, verbose_name='Linha de Ação')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('indicador_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plano_indicador', to='appplano.indicador_estrategico', verbose_name='Indicador Estratégico')),
                ('perspectiva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plano_perspectiva', to='appplano.perspectiva')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plano_pilar', to='appplano.pilar', verbose_name='Pilar')),
                ('responsavel_plano', models.ForeignKey(default='', max_length=60, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Plano')),
            ],
            options={
                'verbose_name': 'Plano de ação',
                'verbose_name_plural': 'Planos de Ações',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Unidade_Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Unidade de Negócio',
                'verbose_name_plural': 'Unidades de Negócios',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Ponto_Critico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, default='', max_length=255, verbose_name='Descrição')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('plano_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto_plano', to='appplano.plano_acao', verbose_name='Plano de Ação')),
            ],
            options={
                'verbose_name': 'Ponto Crítico',
                'verbose_name_plural': 'Pontos Críticos',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='plano_acao',
            name='unidade_negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plano_unidade', to='appplano.unidade_negocio', verbose_name='Unidade de Negócio'),
        ),
        migrations.CreateModel(
            name='Acao_Melhoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, default='', max_length=150, verbose_name='Ação de Melhoria')),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Atrasado', 'Atrasado')], default='Planejado', max_length=12, verbose_name='Status')),
                ('evidencia', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=4, verbose_name='Evidência?')),
                ('arquivo_evidencia', models.FileField(blank=True, upload_to='arquivos_evidencias', verbose_name='Arquivo de Evidência')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ponto_critico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acao_ponto', to='appplano.ponto_critico')),
            ],
            options={
                'verbose_name': 'Ação de Melhoria',
                'verbose_name_plural': 'Ações de Melhorias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Item_Plano_Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=140, verbose_name='O que?')),
                ('como', models.CharField(db_index=True, max_length=150, verbose_name='Como?')),
                ('quem', models.CharField(db_index=True, max_length=140, verbose_name='Quem?')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Finalização')),
                ('onde', models.CharField(db_index=True, max_length=140, verbose_name='Onde?')),
                ('porque', models.CharField(db_index=True, max_length=150, verbose_name='Por que?')),
                ('quanto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quanto?')),
                ('risco_estrategia', models.CharField(db_index=True, max_length=140, verbose_name='Risco à Estratégia')),
                ('evidencia', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=4)),
                ('arquivo_evidencia', models.FileField(blank=True, upload_to='arquivos_evidencias')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Atrasado', 'Atrasado')], default='Planejado', max_length=12)),
                ('plano_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_plano', to='appplano.plano_acao')),
            ],
            options={
                'verbose_name': 'Item do Plano de Ação',
                'verbose_name_plural': 'Itens do Plano',
                'ordering': ('id',),
                'index_together': {('id',)},
            },
        ),
    ]
