# Generated by Django 3.2 on 2023-03-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_plano_acao',
            name='nome',
            field=models.TextField(db_index=True, max_length=140, verbose_name='O que?'),
        ),
    ]
