# Generated by Django 3.2 on 2023-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplano', '0003_alter_plano_acao_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_plano_acao',
            name='nome',
            field=models.CharField(db_index=True, max_length=150, verbose_name='O que?'),
        ),
        migrations.AlterField(
            model_name='plano_acao',
            name='nome',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Linha de Ação'),
        ),
    ]
