# Generated by Django 3.2 on 2023-03-14 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=255)),
                ('descricao', models.TextField(db_index=True, max_length=255, null=True, verbose_name='Descrição')),
                ('dt_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('dt_final', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Finalização')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tarefa_categoria', to='apptarefa.categoria', verbose_name='Categoria')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tarefa_lista', to='apptarefa.lista', verbose_name='Lista')),
                ('membro', models.ForeignKey(default='', max_length=60, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completo', models.BooleanField(default=False)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='checklist_tarefa', to='apptarefa.tarefa')),
            ],
            options={
                'verbose_name': 'Checklist',
                'ordering': ('completo',),
            },
        ),
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bandeira_tarefa', to='apptarefa.tarefa')),
            ],
            options={
                'verbose_name': 'Bandeira',
                'verbose_name_plural': 'Bandeiras',
                'ordering': ('name',),
            },
        ),
    ]
