# Generated by Django 3.2 on 2023-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptarefa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
