# Generated by Django 3.2 on 2023-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptarefa', '0002_checklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandeira',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Nome'),
        ),
    ]
