# Generated by Django 3.2 on 2023-03-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptarefa', '0004_auto_20230314_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='tarefa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membro_tarefa', to='apptarefa.tarefa'),
            preserve_default=False,
        ),
    ]
